t = (0:100)/48e3;
data = zeros(1, length(t));
data(1) = 1;
scale = 2^15 - 1;
[imp_int] = data2hexfile(data, scale, 'imp.txt')
filename = ".\active_hdl\active_hdl\imp_out.txt";
[arr, int_arr] = hexfile2data(filename, scale);
imp_check = filter(Num,1,data);
sqnr = check_data(imp_check(1:end-3), int_arr(4:end));
data_sin = sin(2*pi*1e3*t);
[sin_int] = data2hexfile(data_sin, scale, 'sin.txt');
% data_int = round(data * 2^15 - 1);
% sin_check = filter(Num,1,data);
Num_int = round(Num * 2^15 - 1);
imp_int = round(data * scale);
imp_check_int = filter(Num_int,1,data_int);
psig_in_db = 10*log10(mean(abs(imp_int).^2))
psig_out_db = 10*log10(mean(abs(int_arr).^2))